# Generated by Django 5.2.16 on 2026-07-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='color',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='weight',
        ),
    ]
