# Generated by Django 5.2.16 on 2026-07-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_color_remove_customer_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='dog_name',
            new_name='pet_name',
        ),
    ]
