import requests
from django.conf import settings


def send_sms(number, message):
    """
    Send SMS using iProg SMS API.
    """

    url = "https://sms.iprogtech.com/api/v1/sms_messages"

    payload = {
        "api_token": settings.IPROG_API_TOKEN,
        "phone_number": number,
        "message": message,
    }

    print("========================================")
    print("iProg SMS")
    print("========================================")
    print("API URL:", url)
    print("Phone:", number)
    print("Message:")
    print(message)
    print("========================================")

    try:
        response = requests.post(
            url,
            data=payload,
            timeout=30
        )

        print("iProg STATUS:", response.status_code)
        print("iProg RESPONSE:", response.text)

        response.raise_for_status()

        try:
            result = response.json()

        except ValueError:
            result = {
                "success": response.ok,
                "status_code": response.status_code,
                "response": response.text,
            }

        print("iProg RESULT:", result)

        return result

    except requests.exceptions.RequestException as e:

        print("========================================")
        print("iProg SMS ERROR")
        print("========================================")
        print(str(e))
        print("========================================")

        return {
            "success": False,
            "error": str(e),
        }


def notify_vet(
    customer,
    symptoms,
    reason,
    risk_level="high"
):
    """
    Send emergency notification to veterinarian.
    """

    message = f"""
WE CARE PET CARE
VETERINARY EMERGENCY ALERT

Risk Level:
{risk_level.upper()}

OWNER
Name: {customer.fullname}
Phone: {customer.contact_number}
Address: {customer.address}

DOG
Name: {customer.pet_name}
Breed: {customer.breed}
Sex: {customer.sex}

REPORTED SYMPTOMS
{symptoms}

AI SAFETY ASSESSMENT
{reason}

ACTION REQUIRED
Please contact the owner and provide emergency veterinary assistance.

This emergency alert was generated by We Care Pet Care AI.
""".strip()

    print("========================================")
    print("SENDING VETERINARIAN SMS")
    print("========================================")
    print("Veterinarian:", settings.VETERINARY_PHONE)
    print("========================================")

    return send_sms(
        settings.VETERINARY_PHONE,
        message
    )